---
# Tag filter for the Systems Integration & Operations team.

### Drop specific people from report

skip:

  - mgsimpson@email.arizona.edu

### Rewrite tags

tags:

  #emails:       email
  #Helpline:     helpline
  meeting:      meetings
  #Panopto:      panopto
  scanner:      scanners
  #UAPress:      uapress
  #vac:          vacation
  #VMware:       vmware
  
  #audiovisual:  events
  #av:           events
  #av_consult:   events
  #av_research:  events
  av_setup:     events
  
  #break:        overhead
  #cleaning:     overhead
  #flushot:      overhead
  #food:         overhead
  #comp:         overhead
  #out:          overhead
  #party:        overhead
  paperwork:     overhead
  
  #consulting:   discussions
  #informal:     discussions
  
  #laptop:       staffsup
  #printer:      staffsup
  #refresh:      staffsup
  #purchasing:   staffsup
  
  #commons:      ic
  iccomputers:  ic
  
  #ecommerce:          millennium
  #digitalsignage:     signage
  #read:               learning
  #telephones:         telecom
  #feedback:           liaison
  helpline_followup:  helpline
  hw_scanner:         scanners
  kfs:                uaf
  #lsprfp:             lsp
  reimaging:          lending
  servers:            capacity
  #idonethishell:      effort
  manybadwords:       rooms
  crashcourse:        learning
  ahsl:               lending
  inventory:          assets
  purchasing:         assets
  research:           assets
  software:           assets
  virus:              endpoints
  wifi:               network
...
