---
# Service tree for the Systems Integration & Operations team.
-
  name:     Systems Integration & Operations
  tag:      ops
  branches:
  -
    name:     Client Services & Support
    tag:      clients
    branches:
    -
      name:     Helpline Support
      tag:      helpline
      branches:
    -
      name:     Student Management
      tag:      students
      branches:
    -
      name:     Asset Management
      tag:      assets
      branches:
      -
        name:     Licensing Support
        tag:      licensing
        branches:
      -
        name:     Keyserver Support
        tag:      keyserver
        branches:
      -
        name:     LANDESK Support
        tag:      landesk
        branches:
    -
      name:     Specific Service Support
      tag:      services
      branches:
      -
        name:     Telecommunications Support
        tag:      telecom
        branches:
      -
        name:     Book Scanner Support
        tag:      scanners
        branches:
      -
        name:     Digital Signage Support
        tag:      signage
        branches:
      -
        name:     3D Printer & Scanner Support
        tag:      3dprinting
        branches:
      -
        name:     Lecture Capture Support
        tag:      panopto
        branches:
      -
        name:     Room Reservation Services Support
        tag:      dibs
        branches:
    -
      name:     Endpoint Support
      tag:      endpoints
      branches:
      -
        name:     Staff Workstations & Laptops
        tag:      staff
        branches:
      -
        name:     Specific Installations
        tag:      installations
        branches:
        -
          name:     Meeting Rooms
          tag:      rooms
          branches:
        -
          name:     Information Commons
          tag:      ic
          branches:
        -
          name:     Technology Lending
          tag:      lending
          branches:
    -
      name:     Event Support
      tag:      events
      branches:
  -
    name:     Systems & Application Delivery
    tag:      sysapp
    branches:
    -
      name:     Systems Integration & Administration
      tag:      systems
      branches:
      -
        name:     Capacity Provisioning
        tag:      capacity
        branches:
        -
          name:     Networking
          tag:      network
          branches:
        -
          name:     Computing
          tag:      compute
          branches:
        -
          name:     Storage
          tag:      storage
          branches:
        -
          name:     Backup
          tag:      backup
          branches:
      -
        name:     Platform Support
        tag:      platforms
        branches:
        -
          name:     Virtualization Solutions
          tag:      virtualization
          branches:
          -
            name:     VMware Administration
            tag:      vmware
            branches:
        -
          name:     Operating Systems
          tag:      os
          branches:
          -
            name:     Linux Server Administration
            tag:      linux
            branches:
          -
            name:     Windows Server Administration
            tag:      windows
            branches:
        -
          name:     Container Services
          tag:      containers
          branches:
          -
            name:     Kubernetes Administration
            tag:      kubernetes
            branches:
      -
        name:     Operational Management
        tag:      operations
        branches:
        -
          name:     Configuration Management
          tag:      configuration
          branches:
          -
            name:     Ansible Configuration Management
            tag:      ansible
            branches:
        -
          name:     Monitoring & Alerting
          tag:      monitoring
          branches:
        -
          name:     Logging Services
          tag:      logging
          branches:
        -
          name:     Security Management
          tag:      security
          branches:
          -
            name:     PCI Compliance Verification
            tag:      pci
            branches:
    -
      name:     Application Delivery
      tag:      applications
      branches:
      -
        name:     Service Delivery
        tag:      delivery
        branches:
        -
          name:     Authentication & Authorization Services
          tag:      authnz
          branches:
        -
          name:     Document Management Services
          tag:      documents
          branches:
          -
            name:     Box Service
            tag:      box
            branches:
          -
            name:     DocuWare Service
            tag:      docuware
            branches:
          -
            name:     SharePoint Service
            tag:      sharepoint
            branches:
        -
          name:     Library Services Platforms
          tag:      lsp
          branches:
          -
            name:     Millennium Service
            tag:      millennium
            branches:
            -
              name:     GreenGlass Collection Analysis
              tag:      greenglass
              branches:
          -
            name:     Illiad Service
            tag:      illiad
            branches:
          -
            name:     OCLC Services
            tag:      oclc
            branches:
        -
          name:     Proxy Services
          tag:      proxy
          branches:
          -
            name:     EZProxy Service
            tag:      ezproxy
            branches:
        -
          name:     Digital Preservation Services
          tag:      preservation
          branches:
          -
            name:     Rosetta Service
            tag:      rosetta
            branches:
        -
          name:     Hosted Data
          tag:      hosted
          branches:
          -
            name:     Hosted Databases
            tag:      databases
            branches:
          -
            name:     Hosted Journals
            tag:      journals
            branches:
            -
              name:     OJS Service
              tag:      ojs
              branches:
          -
            name:     Hosted Websites
            tag:      websites
            branches:
            -
              name:     Drupal Services
              tag:      drupal
              branches:
      -
        name:     Data Integration
        tag:      etl
        branches:
        -
          name:     Amer-X Facilities Security
          tag:      amerx
          branches:
        -
          name:     UAccess Financials
          tag:      uaf
          branches:
  -
    name:     Overhead Activities
    tag:      overhead
    branches:
    -
      name:     Leave Time
      tag:      leave
      branches:
      -
        name:     Sick Leave
        tag:      sick
        branches:
      -
        name:     Holidays
        tag:      holiday
        branches:
      -
        name:     Vacations
        tag:      vacation
        branches:
    -
      name:     Communication & Coordination
      tag:      communication
      branches:
      -
        name:     Email
        tag:      email
        branches:
      -
        name:     Group Meetings
        tag:      meetings
        branches:
      -
        name:     One-On-One Conversations
        tag:      1on1
        branches:
      -
        name:     Informal Discussions
        tag:      discussions
        branches:
      - 
        name:     Liaison Activities
        tag:      liaison
        branches:
        -
          name:     Internal Liaison
          tag:      internal
          branches:
          -
            name:     Library Cabinet
            tag:      cabinet
            branches:
          - 
            name:     Library Council of Appointed Professionals
            tag:      lcap
            branches:
          - 
            name:     Compensation Philosophy Task Force
            tag:      cptf
            branches:
          -
            name:     Diversity, Social Justice, & Equity Council
            tag:      dsjec
            branches:
          - 
            name:     Access & Information Services
            tag:      ais
            branches:
          - 
            name:     Delivery, Description, & Acquisitions
            tag:      dda
            branches:
          -
            name:     Facilities Planning & Management
            tag:      fpm
            branches:
          - 
            name:     Office of Digital Information & Stewardship
            tag:      odis
            branches:
          - 
            name:     Research & Learning
            tag:      randl
            branches:
          - 
            name:     Special Collections
            tag:      speccoll
            branches:
          - 
            name:     UA Press
            tag:      uapress
            branches:
        -
          name:     External Liaison
          tag:      external
          branches:
          -
            name:     Deans Information Technology Council
            tag:      ditc
            branches:
          - 
            name:     UA IT Special Interest Groups
            tag:      itsigs
            branches:
          - 
            name:     IT Security Managers Council
            tag:      itsm
            branches:
          -
            name:     UA IT Summit
            tag:      itsummit
            branches:
    -
      name:     Professional Development
      tag:      profdev
      branches:
      -
        name:     Informal Learning
        tag:      learning
        branches:
      -
        name:     Formal Training
        tag:      training
        branches:
      -
        name:     Cross-Training & Transitioning
        tag:      crosstraining
        branches:
      -
        name:     Teaching Activities
        tag:      teaching
        branches:
      -
        name:     Conference Attendance
        tag:      conferences
        branches:
    -
      name:     Organizational Development
      tag:      organization
      branches:
      -
        name:     General Administrative Tasks
        tag:      admin
        branches:
      -
        name:     Budget Development
        tag:      budget
        branches:
      -
        name:     Projects & Planning
        tag:      planning
        branches:
      -
        name:     Personnel Management
        tag:      personnel
        branches:
      -
        name:     Process Analysis
        tag:      process
        branches:
      -
        name:     Timesheets
        tag:      timesheets
        branches:
    -
      name:     Internal Toolsmithing
      tag:      tools
      branches:
      -
        name:     Effort Reporting
        tag:      effort
        branches:
      -
        name:     Enterprise Service Management
        tag:      esm
        branches:
...
