---
# Service tree for the Systems Integration & Operations team.
-
  name:     Systems Integration & Operations
  tag:      ops
  branches:
  -
    name:     Overhead Activities
    tag:      overhead
    branches:
    -
      name:     Leave Time
      tag:      leave
      branches:
      -
        name:     Sick Leave
        tag:      sick
        branches:
      -
        name:     Holidays
        tag:      holiday
        branches:
      -
        name:     Vacations
        tag:      vacation
        branches:
    -
      name:     Communication & Coordination
      tag:      communication
      branches:
      -
        name:     Email
        tag:      email
        branches:
      -
        name:     Group Meetings
        tag:      meetings
        branches:
      -
        name:     One-On-One Conversations
        tag:      1on1
        branches:
      -
        name:     Informal Discussions
        tag:      discussions
        branches:
      - 
        name:     Liaison Activities
        tag:      liaison
        branches:
        -
          name:     Internal Liaison
          tag:      internal
          branches:
          -
            name:     Library Cabinet
            tag:      cabinet
            branches:
          - 
            name:     Library Council of Appointed Professionals
            tag:      lcap
            branches:
          - 
            name:     Access & Information Services
            tag:      ais
            branches:
          - 
            name:     Delivery, Description, & Acquisitions
            tag:      dda
            branches:
          -
            name:     Facilities Planning & Management
            tag:      fpm
            branches:
          - 
            name:     Office of Digital Information & Stewardship
            tag:      odis
            branches:
          - 
            name:     Research & Learning
            tag:      randl
            branches:
          - 
            name:     Special Collections
            tag:      speccoll
            branches:
          - 
            name:     UA Press
            tag:      uapress
            branches:
        -
          name:     External Liaison
          tag:      external
          branches:
          -
            name:     Deans Information Technology Council
            tag:      ditc
            branches:
          - 
            name:     UA IT Special Interest Groups
            tag:      itsigs
            branches:
          - 
            name:     IT Security Managers Council
            tag:      itsm
            branches:
          -
            name:     UA IT Summit
            tag:      itsummit
            branches:
    -
      name:     Professional Development
      tag:      profdev
      branches:
      -
        name:     Informal Learning
        tag:      learning
        branches:
        -
          name:     The Crash Course
          tag:      crashcourse
          branches:
      -
        name:     Formal Training
        tag:      training
        branches:
      -
        name:     Teaching Activities
        tag:      teaching
        branches:
      -
        name:     Conference Attendance
        tag:      conference
        branches:
    -
      name:     Organizational Development
      tag:      organization
      branches:
      -
        name:     General Administrative Tasks
        tag:      admin
        branches:
      -
        name:     Budget Development
        tag:      budget
        branches:
      -
        name:     Projects & Planning
        tag:      planning
        branches:
      -
        name:     Personnel Management
        tag:      personnel
        branches:
      -
        name:     Process Analysis
        tag:      process
        branches:
      -
        name:     Timesheets
        tag:      timesheets
        branches:
    -
      name:     Internal Toolsmithing
      tag:      tools
      branches:
      -
        name:     Effort Reporting
        tag:      effort
        branches:
      -
        name:     Enterprise Service Management
        tag:      esm
        branches:
  -
    name:     Client Services & Support
    tag:      clients
    branches:
    -
      name:     Helpline Support
      tag:      helpline
      branches:
    -
      name:     Student Management
      tag:      students
      branches:
    -
      name:     Software Management
      tag:      software
      branches:
      -
        name:     Licensing Support
        tag:      licensing
        branches:
      -
        name:     Keyserver Support
        tag:      keyserver
        branches:
    -
      name:     Specific Service Support
      tag:      services
      branches:
      -
        name:     Telecommunications Support
        tag:      telecom
        branches:
      -
        name:     Book Scanner Support
        tag:      scanners
        branches:
      -
        name:     Digital Signage Support
        tag:      signage
        branches:
      -
        name:     3D Printer & Scanner Support
        tag:      3dprinting
        branches:
      -
        name:     Lecture Capture Support
        tag:      panopto
        branches:
      -
        name:     Room Reservation Services Support
        tag:      dibs
        branches:
    -
      name:     Event Support
      tag:      events
      branches:
    -
      name:     Endpoint Support
      tag:      endpoints
      branches:
      -
        name:     Staff Endpoints Support
        tag:      staffsup
        branches:
      -
        name:     Specific Installations
        tag:      installations
        branches:
        -
          name:     Meeting Rooms
          tag:      rooms
          branches:
        -
          name:     Information Commons
          tag:      ic
          branches:
        -
          name:     Equipment Lending
          tag:      lending
          branches:
  -
    name:     Systems Integration & Operations
    tag:      systems
    branches:
    -
      name:     Capacity Provisioning
      tag:      capacity
      branches:
      -
        name:     Networking
        tag:      network
        branches:
      -
        name:     Computing
        tag:      compute
        branches:
      -
        name:     Storage
        tag:      storage
        branches:
      -
        name:     Backup
        tag:      backup
        branches:
    -
      name:     Platform Support
      tag:      platforms
      branches:
      -
        name:     Virtualization Solutions
        tag:      virtual
        branches:
        -
          name:     VMware Administration
          tag:      vmware
          branches:
      -
        name:     Operating System Administration
        tag:      sysadmin
        branches:
        -
          name:     Linux Server Administration
          tag:      linux
          branches:
        -
          name:     Windows Server Administration
          tag:      windows
          branches:
    -
      name:     Operational Management
      tag:      operations
      branches:
      -
        name:     Configuration Management
        tag:      configuration
        branches:
        -
          name:     LANDESK Systems Management
          tag:      landesk
          branches:
      -
        name:     Logging Services
        tag:      logging
        branches:
      -
        name:     Monitoring Services
        tag:      monitoring
        branches:
      -
        name:     Security Management
        tag:      security
        branches:
        -
          name:     PCI Compliance Verification
          tag:      pci
          branches:
  -
    name:     Application Delivery
    tag:      applications
    branches:
    -
      name:     Library Authentication & Authorization Services
      tag:      authnz
      branches:
    -
      name:     Library Document Management Services
      tag:      documents
      branches:
      -
        name:     Box Service
        tag:      box
        branches:
      -
        name:     DocuWare Service
        tag:      docuware
        branches:
    -
      name:     Library Services Platforms
      tag:      lsp
      branches:
      -
        name:     Millennium Library Services Platform
        tag:      millennium
        branches:
      -
        name:     Illiad Interlibrary Loan Service
        tag:      illiad
        branches:
      -
        name:     OCLC Services
        tag:      oclc
        branches:
    -
      name:     Library Hosted Databases Services
      tag:      databases
      branches:
    -
      name:     Library Proxy Services
      tag:      ezproxy
      branches:
    -
      name:     Library Preservation Services
      tag:      rosetta
      branches:
    -
      name:     Library Hosted Journals Services
      tag:      ojs
      branches:
    -
      name:     Data Integration Services
      tag:      etl
      branches:
      -
        name:     Amer-X Facilities Security
        tag:      amerx
        branches:
      -
        name:     GreenGlass Collection Analysis
        tag:      greenglass
        branches:
      -
        name:     UAccess Financials
        tag:      financials
        branches:
...
