#!/usr/bin/env python

import argparse
import ireportedthis

parser = argparse.ArgumentParser( description='Extract and pretty-print IReportedThis schemas.' )
parser.add_argument( '--schema', '-s', required = True, help = 'path to schema file' )
parser.add_argument( '--tagsonly', '-t', action = 'store_true', help = 'only print tags' )
args = parser.parse_args()

s = ireportedthis.YAMLSchema( args.schema )
s.pretty_print( args.tagsonly )
