#!/usr/bin/env python

import argparse
import ireportedthis

parser = argparse.ArgumentParser( description='Produce an IReportedThis report.' )
parser.add_argument( '--population', '-p', required = True, help = 'path to population file' )
parser.add_argument( '--schema', '-s', required = True, help = 'path to schema file' )
parser.add_argument( '--days', '-d', required = True, type = int, help = 'number of working days in sampling period' )
parser.add_argument( '--fte', '-f', required = True, type = int, help = 'number of FTE deployed across sampling period' )
parser.add_argument( '--cumulative', '-c', action = 'store_true', help = 'turn on cumulative reporting' )
parser.add_argument( '--verbose', '-v', action = 'store_true', help = 'turn on verbose reporting' )
parser.add_argument( '--rejected', '-r', action = 'store_true', help = 'show entries rejected during population parse' )
args = parser.parse_args()

p = ireportedthis.CSVPopulation( args.population )
s = ireportedthis.YAMLSchema( args.schema )
r = ireportedthis.Report( p, s, args.days, args.fte )

r.print_report( cumulative = args.cumulative, verbose = args.verbose, rejected = args.rejected )
